// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230702074230_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 4,
                            Breed = "Mixed",
                            Name = "Barley",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            Breed = "American Shorthair",
                            Name = "Pancake",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            Breed = "Terrier",
                            Name = "Rory",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 8,
                            Breed = "Maine Coon",
                            Name = "Fil",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 9,
                            Breed = "Shi-Tzu",
                            Name = "Tugger",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Breed = "American Bull Terrier",
                            Name = "Ody",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
